server.port: 8443

spring.application.name: gateway

spring.ssl.bundle.jks.gateway:
  key:
    alias: localhost
  keystore:
    type: PKCS12
    location: classpath:keystore/edge.p12
    password: password

server.ssl.bundle: gateway

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost
  auth-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud.gateway.routes:
- id: product-composite
  predicates:
    - Path=/product-composite/**
  uri: lb://product-composite

- id: oauth2-server
  predicates:
    - Path=/oauth2/**
  uri: lb://auth-server

- id: oauth2-login
  predicates:
    - Path=/login/**
  uri: lb://auth-server

- id: oauth2-error
  predicates:
    - Path=/error/**
  uri: lb://auth-server

- id: product-composite-swagger-ui
  predicates:
    - Path=/openapi/**
  uri: lb://product-composite

- id: eureka-api
  predicates:
    - Path=/eureka/api/{segment}
  uri: http://${app.eureka-server}:8761
  filters:
    - SetPath=/eureka/{segment}

- id: eureka-web-start
  predicates:
    - Path=/eureka/web
  uri: http://${app.eureka-server}:8761
  filters:
    - SetPath=/

- id: eureka-web-other
  predicates:
    - Path=/eureka/**
  uri: http://${app.eureka-server}:8761


- id: host_route_200
  predicates:
    - Host=i.feel.lucky:8080
    - Path=/headerrouting/**
  uri: http://httpstat.us
  filters:
    - SetPath=/200

- id: host_route_418
  predicates:
    - Host=im.a.teapot:8080
    - Path=/headerrouting/**
  uri: http://httpstat.us
  filters:
    - SetPath=/418

- id: host_route_501
  predicates:
    - Path=/headerrouting/**
  uri: http://httpstat.us
  filters:
    - SetPath=/501

spring.security.oauth2.resourceserver.jwt.issuer-uri: https://dev-7ycdugibfto3rgic.us.auth0.com/

management.endpoint.gateway.enabled: true
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring.config.activate.on-profile: docker

app:
  eureka-server: eureka
  auth-server: auth-server
