server.port: 8080

spring.application.name: gateway

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud.gateway.routes:
- id: product-composite
  predicates:
    - Path=/product-composite/**
  uri: lb://product-composite

- id: product-composite-swagger-ui
  predicates:
    - Path=/openapi/**
  uri: lb://product-composite

- id: eureka-api
  predicates:
    - Path=/eureka/api/{segment}
  uri: http://${app.eureka-server}:8761
  filters:
    - SetPath=/eureka/{segment}

- id: eureka-web-start
  predicates:
    - Path=/eureka/web
  uri: http://${app.eureka-server}:8761
  filters:
    - SetPath=/

- id: eureka-web-other
  predicates:
    - Path=/eureka/**
  uri: http://${app.eureka-server}:8761


- id: host_route_200
  predicates:
    - Host=i.feel.lucky:8080
    - Path=/headerrouting/**
  uri: http://httpstat.us
  filters:
    - SetPath=/200

- id: host_route_418
  predicates:
    - Host=im.a.teapot:8080
    - Path=/headerrouting/**
  uri: http://httpstat.us
  filters:
    - SetPath=/418

- id: host_route_501
  predicates:
    - Path=/headerrouting/**
  uri: http://httpstat.us
  filters:
    - SetPath=/501

management.endpoint.gateway.enabled: true
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring.config.activate.on-profile: docker

app.eureka-server: eureka
