spring.application.name: recommendation-service

server.port: 8002
server.error.include-message: always

logging:
  level:
    root: INFO
    study.microservices: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db
  auto-index-creation: true

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.data.mongodb:
  host: mongodb
  auto-index-creation: true