spring.application.name: review-service

server.port: 8003
server.error.include-message: always

logging:
  level:
    root: INFO
    study.microservices: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

---
spring.config.activate.on-profile: docker

server.port: 8080
